export const IMPORT_CSV_REQUEST = "IMPORT_CSV_REQUEST";
export const IMPORT_CSV_SUCCESS = "IMPORT_CSV_SUCCESS";
export const IMPORT_CSV_FAIL = "IMPORT_CSV_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";