export const IMPORT_CSV_REQUEST = "IMPORT_CSV_REQUEST";
export const IMPORT_CSV_SUCCESS = "IMPORT_CSV_SUCCESS";
export const IMPORT_CSV_FAIL = "IMPORT_CSV_FAIL";

export const GET_CSV_REQUEST = "GET_CSV_REQUEST";
export const GET_CSV_SUCCESS = "GET_CSV_SUCCESS";
export const GET_CSV_FAIL = "GET_CSV_FAIL";

export const DELETE_ROW_REQUEST = "DELETE_ROW_REQUEST";
export const DELETE_ROW_SUCCESS = "DELETE_ROW_SUCCESS";
export const DELETE_ROW_FAIL = "DELETE_ROW_FAIL";
export const DELETE_ROW_RESET = "DELETE_ROW_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";